#!/usr/bin/env python3
"""Draw the Teams screen's "5P" controller label and "E Team" alliance label
from the game's "4P" and "D Team" sprites, into src/five_art.rs.

Usage: art.py <rom.gba>   (the ROM is read for the two original sprites)

Each picture is edited as text, one character per pixel (colour index in hex,
. for 0), over the original's tiles, then written back as 4bpp OBJ tiles in
the original's 1D layout.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FOUR_P = 0x080F9004  # 4 tiles, 16x16 (2x2)
D_TEAM = 0x080FFCC4  # 16 tiles 32x32, then 8 tiles 16x32


def tiles(rom, a, n):
    return [bytearray(rom[a - 0x08000000 + 32 * i:a - 0x08000000 + 32 * i + 32]) for i in range(n)]


def to_grid(ts, w, h):
    g = [[0] * (w * 8) for _ in range(h * 8)]
    for y in range(h * 8):
        for x in range(w * 8):
            b = ts[(y // 8) * w + x // 8][(y % 8) * 4 + (x % 8) // 2]
            g[y][x] = (b >> 4) if x & 1 else (b & 15)
    return g


def from_grid(g, w, h):
    out = bytearray()
    for ty in range(h):
        for tx in range(w):
            for y in range(8):
                for x in range(0, 8, 2):
                    lo, hi = g[ty * 8 + y][tx * 8 + x], g[ty * 8 + y][tx * 8 + x + 1]
                    out.append(lo | (hi << 4))
    return bytes(out)


def paint(g, x0, y0, rows):
    for dy, row in enumerate(rows):
        for dx, c in enumerate(row):
            if c != ' ':
                g[y0 + dy][x0 + dx] = 0 if c == '.' else int(c, 16)


# "5" in the 4P label's style (outline f, fill 6, highlight 7), over the 4.
FIVE = [
    ".fffffff",
    "f766666f",
    "f66fffff",
    "f666666f",
    "f666666f",
    "fffff66f",
    "f666666f",
    "f666667f",
    "ffffffff",
    ".fffffff",
]

# "E" in the D Team label's style (outline f, inner outline 1, fill 5, shade
# c/e), over the D; columns 2..18 of rows 6..24.
E = [
    "ffffffffffffffff.",
    "f1111111111111cef",
    "f155555555555511f",
    "f155551111111111f",
    "f155551ffffffffff",
    "f155551f.........",
    "f155551111111ef..",
    "f15555555555511f.",
    "f15555555555511f.",
    "f155551111111ef..",
    "f155551f.........",
    "f155551ffffffffff",
    "f155551111111111f",
    "f155555555555511f",
    "f155555555555511f",
    "f1111111111111cef",
    "effffffffffffffff",
    ".effffffffffffffe",
]


def main():
    rom = open(sys.argv[1], 'rb').read()
    p = to_grid(tiles(rom, FOUR_P, 4), 2, 2)
    # clear the 4 (columns 0..6, rows 2..13), then paint the 5
    for y in range(2, 14):
        for x in range(0, 7):
            p[y][x] = 0
    paint(p, 0, 2, FIVE)
    five_p = from_grid(p, 2, 2)

    t = tiles(rom, D_TEAM, 24)
    big = to_grid(t[:16], 4, 4)
    for y in range(6, 25):
        for x in range(2, 19):
            big[y][x] = 0
    paint(big, 2, 6, E)
    e_team = from_grid(big, 4, 4) + b''.join(t[16:])

    out = os.path.join(HERE, '..', 'src', 'five_art.rs')
    with open(out, 'w') as o:
        o.write('// Generated by five/art.py; do not edit.\n\n')
        for name, data, what in [('FIVE_P', five_p, '"5P": 4 tiles, 16x16'), ('E_TEAM', e_team, '"E Team": 16 tiles 32x32, then 8 tiles 16x32')]:
            o.write(f'/// {what}, 4bpp.\npub const {name}: [u8; {len(data)}] = [\n')
            for i in range(0, len(data), 16):
                o.write('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',\n')
            o.write('];\n\n')
    for name, g in [('5P', p), ('E Team', big)]:
        print(name)
        for row in g:
            print(''.join('.' if v == 0 else '%x' % v for v in row))


main()
