#!/usr/bin/env python3
"""Draw the terrain-panel names of tangoAW2's Black Crystal and Black Obelisk
("Crystal", "Obelisk", 32x16 in the game's panel font) into
src/obelisk_art.rs.

Their pictures are not here: they are Dual Strike's, imported by each
player from their own Advance Wars: Dual Strike ROM (src/ds_art.rs).

Usage: obelisk_art.py [preview.png]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
KEY = {'.': 0, 'w': 1, 'F': 15}


# Terrain-panel names (32x16, the font's style: a big capital, then small
# letters at a 4-pixel pitch, white (1) outlined (f)). Fill pixels only; the
# outline is added round them.
BIG = {
    'C': [".1111.", "11..11", "11....", "11....", "11....", "11....", "11..11", ".1111."],
    'O': [".1111.", "11..11", "11..11", "11..11", "11..11", "11..11", "11..11", ".1111."],
}
SMALL = {  # rows 8..11 (and a descender row 12), 3 wide
    'r': ["1.1", "11.", "1..", "1.."],
    'y': ["1.1", "1.1", "111", "..1", "11."],
    's': [".11", "11.", ".11", "11."],
    't': [".1.", "111", ".1.", ".11"],
    'a': [".11", "1.1", "1.1", ".11"],
    'e': [".1.", "111", "1..", ".11"],
    'i': [".1.", ".1.", ".1.", ".1."],
    'k': ["1.1", "11.", "11.", "1.1"],
}
TALL = {'l': 4, 'b': 4, 'k': 4, 'i': 0}  # extra rows above for tall letters


def name(word):
    g = [[0] * 32 for _ in range(16)]
    for dy, row in enumerate(BIG[word[0]]):
        for dx, c in enumerate(row):
            if c == '1':
                g[3 + dy][1 + dx] = 1
    for n, ch in enumerate(word[1:]):
        x0 = 8 + 4 * n
        if ch == 'l':
            for y in range(4, 12):
                g[y][x0 + 1] = 1
            g[11][x0 + 2] = 1
            continue
        if ch == 'b':
            for y in range(4, 12):
                g[y][x0] = 1
            rows = ["11.", "1.1", "1.1", "11."]
        else:
            rows = SMALL[ch]
        if ch == 'k':
            for y in range(4, 8):
                g[y][x0] = 1
        if ch == 'i':
            g[6][x0 + 1] = 1
        for dy, row in enumerate(rows):
            for dx, c in enumerate(row):
                if c == '1':
                    g[8 + dy][x0 + dx] = 1
    out = [[0] * 32 for _ in range(16)]
    for y in range(16):
        for x in range(32):
            if g[y][x]:
                out[y][x] = 1
            elif any(0 <= y + j < 16 and 0 <= x + i < 32 and g[y + j][x + i] for j in (-1, 0, 1) for i in (-1, 0, 1)):
                out[y][x] = 15
    return [''.join('.' if v == 0 else ('w' if v == 1 else 'F') for v in r) for r in out]


def tiles(rows):
    h, w = len(rows), len(rows[0])
    out = bytearray()
    for ty in range(h // 8):
        for tx in range(w // 8):
            for y in range(8):
                for x in range(0, 8, 2):
                    a = KEY[rows[ty * 8 + y][tx * 8 + x]]
                    b = KEY[rows[ty * 8 + y][tx * 8 + x + 1]]
                    out.append(a | (b << 4))
    return bytes(out)


def main():
    out = os.path.join(HERE, '..', 'src', 'obelisk_art.rs')
    with open(out, 'w') as o:
        o.write('// Generated by five/obelisk_art.py; do not edit.\n\n')
        for name_, rows, what in [('CRYSTAL_NAME', name('Crystal'), 'Terrain-panel name, 32x16 (4x2 tiles), font colours'),
                                  ('OBELISK_NAME', name('Obelisk'), 'Terrain-panel name, 32x16 (4x2 tiles), font colours')]:
            data = tiles(rows)
            o.write(f'/// {what}.\npub const {name_}: [u8; {len(data)}] = [\n')
            for i in range(0, len(data), 16):
                o.write('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',\n')
            o.write('];\n\n')
    if len(sys.argv) > 1:
        from PIL import Image
        im = Image.new('RGB', (40, 40), (160, 200, 120))
        for img_rows, oy in [(name('Crystal'), 2), (name('Obelisk'), 22)]:
            for y, r in enumerate(img_rows):
                for x, c in enumerate(r):
                    if c != '.':
                        im.putpixel((4 + x, oy + y), (40, 40, 60) if c == 'F' else (248, 248, 248))
        im.resize((320, 320), Image.NEAREST).save(sys.argv[1])


main()
